name: Track Release Downloads

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12 PM UTC
  workflow_dispatch:

jobs:
  log-downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Get Release Data
        run: |
          curl -s -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases" \
          | jq '.[].assets[] | {name, download_count}' > downloads.json

      - name: Commit & Push Logs
        run: |
          git add downloads.json
          git diff --quiet || git commit -m "Updated download logs"
          git push origin main  # Replace 'main' with your desired branch if different